//! Transparency obligations per EU AI Act Chapter IV.

use serde::{Deserialize, Serialize};

/// Configuration for transparency and information provision.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransparencyConfig {
    pub disclose_ai_interaction: bool,
    pub disclose_generated_content: bool,
    pub disclose_limitations: bool,
}

impl Default for TransparencyConfig {
    fn default() -> Self {
        Self {
            disclose_ai_interaction: true,
            disclose_generated_content: true,
            disclose_limitations: true,
        }
    }
}

/// End-user disclosure text (Article 52 et al.).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EndUserDisclosure {
    pub interaction_notice: String,
    pub generated_content_notice: Option<String>,
    pub limitations_notice: Option<String>,
}

impl EndUserDisclosure {
    pub fn for_limited_risk() -> Self {
        Self {
            interaction_notice: "You are interacting with an AI system.".to_string(),
            generated_content_notice: Some("Content may be generated by AI.".to_string()),
            limitations_notice: None,
        }
    }

    pub fn for_high_risk(limitations: &str) -> Self {
        Self {
            interaction_notice: "This is a high-risk AI system subject to EU AI Act. Human oversight is available.".to_string(),
            generated_content_notice: Some("Outputs have been generated by AI.".to_string()),
            limitations_notice: Some(limitations.to_string()),
        }
    }
}
